otreeutils/admin_extensions/urls.py
"""
Custom URLs that add hooks to session data monitor extensions.

Feb. 2021, Markus Konrad <markus.konrad@wzb.eu>
"""

from django.conf.urls import url
from otree.urls import urlpatterns

from . import views


# define patterns with name, URL pattern and view class
patterns_conf = {
    'SessionData': (r"^SessionData/(?P<code>[a-z0-9]+)/$", views.SessionDataExtension),
    'SessionDataAjax': (r"^session_data/(?P<code>[a-z0-9]+)/$", views.SessionDataAjaxExtension),
}

# exclude oTree's original patterns with the same names
urlpatterns = [pttrn for pttrn in urlpatterns if pttrn.name not in patterns_conf.keys()]

# add the patterns
for name, (pttrn, viewclass) in patterns_conf.items():
    urlpatterns.append(url(pttrn, viewclass.as_view(), name=name))

pt3/models.py
from otree.api import (
    models,
    widgets,
    BaseConstants,
    BaseSubsession,
    BaseGroup,
    BasePlayer,
    Currency as c,
    currency_range,
)

import random


author = 'Yuki Takahashi'

doc = """
Group round.
"""


class Constants(BaseConstants):
    name_in_url = 'pt1_VA'
    players_per_group = 2
    num_rounds = 20


class Subsession(BaseSubsession):
    def group_by_arrival_time_method(self, waiting_players):
        import itertools  # import itertools for groupby()
        import json  # import json for loads
        # define several functions to be used as sorting keys
        def sorting_key_both(pl):  # sort players by mygrp and mygid
            return [pl.participant.vars['mygrp'], pl.participant.vars['mygid']]
        def sorting_key_grp(pl):  # sort players by mygrp
            return pl.participant.vars['mygrp']
        def sorting_key_gid(pl):  # sort players by mygid
            return pl.participant.vars['mygid']
        waiting_players.sort(key=sorting_key_both)
        # create a list in which each element is a list of players belonging to the same mygrp, from grp2 to grpN
        waiting_players_grped = [list(g) for k, g in itertools.groupby(waiting_players, key=sorting_key_grp)]
        # sort the list so that longest list group comes first
        waiting_players_grped.sort(reverse=True, key=lambda x: len(x))
        print('waiting players with the largest group in the first:', waiting_players_grped)
        # create a list of mygrp
        waiting_players_key = [int(k) for k, g in itertools.groupby(waiting_players, key=sorting_key_grp)]
        print('waiting groups:', waiting_players_key)
        # choose the first group
        waiting_grp = waiting_players_grped[0]
        waiting_grp_num = waiting_players_grped[0][0].participant.vars['mygrp']
        pairs = [int(i) for i in json.loads(waiting_players_grped[0][0].participant.vars['mypairs'])]
        waiting_grp.sort(key=sorting_key_gid)
        ind = [i.participant.vars['mygid'] for i in waiting_grp]
        print('Check if there is any match among waiting players of group', waiting_grp_num)
        if pairs[0] in ind and pairs[1] in ind:
            to_be_grpd = [waiting_grp[ind.index(pairs[0])], waiting_grp[ind.index(pairs[1])]]
        elif pairs[2] in ind and pairs[3] in ind:
            to_be_grpd = [waiting_grp[ind.index(pairs[2])], waiting_grp[ind.index(pairs[3])]]
        elif pairs[4] in ind and pairs[5] in ind:
            to_be_grpd = [waiting_grp[ind.index(pairs[4])], waiting_grp[ind.index(pairs[5])]]
        elif pairs[6] in ind and pairs[7] in ind:
            to_be_grpd = [waiting_grp[ind.index(pairs[6])], waiting_grp[ind.index(pairs[7])]]
        else:
            to_be_grpd = []
        if len(to_be_grpd) == 2:
            print('WE PAIR GROUP', waiting_grp_num, 's FOLLOWING PLAYERS:', to_be_grpd)
            return to_be_grpd


class Group(BaseGroup):
    # a variable to flag last round
    last_round = models.BooleanField()
    # variables for the puzzle
    starting_player = models.IntegerField()
    move_history = models.LongStringField()
    move_histories_disagree = models.BooleanField()
    puzzle_solved = models.BooleanField(initial=False)

    # verify that the moves are stored correctly
    def verify_stored_moves(self):
        p1 = self.get_player_by_id(1)
        p2 = self.get_player_by_id(2)
        if p1.move_history == p2.move_history:
            self.move_history = p1.move_history
            self.move_histories_disagree = False
        else:
            self.move_histories_disagree = True
        if p1.puzzle_solved or p2.puzzle_solved:
            self.puzzle_solved = True
            p1.puzzle_solved = True
            p2.puzzle_solved = True
        else:
            self.puzzle_solved = False


    # functions to flag the last round, this occurs when a puzzle is unsolved due to timeout
    def check_results(self):
        self.verify_stored_moves()
        if self.puzzle_solved == 1:
            for p in self.get_players():
                p.puzzles_solved_pt3 = self.round_number
                p.pass_variable()
        if self.puzzle_solved == 0:
            self.last_round = 1

    def puzzle_to_play(self, formatting):
        if self.round_number == 1:
            my_puzzle = [[1, 2, None], [7, 5, 3], [8, 4, 6]]
        if self.round_number == 2:
            my_puzzle = [[4, 1, 2], [7, 5, 3], [8, 6, None]]
        if self.round_number == 3:
            my_puzzle = [[1, 2, 3], [None, 7, 4], [8, 6, 5]]
        if self.round_number == 4:
            my_puzzle = [[1, 2, 3], [5, 8, 7], [4, None, 6]]
        if self.round_number == 5:
            my_puzzle = [[2, 7, 3], [1, None, 6], [5, 4, 8]]
        if self.round_number == 6:
            my_puzzle = [[5, 1, 3], [4, None, 6], [7, 2, 8]]
        if self.round_number == 7:
            my_puzzle = [[1, 5, 2], [7, 3, 6], [8, None, 4]]
        if self.round_number == 8:
            my_puzzle = [[1, 2, 3], [None, 7, 6], [8, 5, 4]]
        if self.round_number == 9:
            my_puzzle = [[1, 7, 3], [4, None, 5], [8, 2, 6]]
        if self.round_number == 10:
            my_puzzle = [[2, 3, 6], [4, None, 5], [7, 1, 8]]
        if self.round_number == 11:
            my_puzzle = [[2, 3, 6], [7, 5, None], [1, 4, 8]]
        if self.round_number == 12:
            my_puzzle = [[1, 3, 4], [None, 7, 2], [8, 6, 5]]
        if self.round_number == 13:
            my_puzzle = [[4, 6, 1], [7, None, 2], [5, 8, 3]]
        if self.round_number == 14:
            my_puzzle = [[7, 4, 1], [3, None, 2], [8, 5, 6]]
        if self.round_number == 15:
            my_puzzle = [[7, 1, 3], [None, 2, 4], [6, 5, 8]]
        if self.round_number == 16:
            my_puzzle = [[4, 1, 2], [None, 3, 6], [8, 5, 7]]
        if self.round_number == 17:
            my_puzzle = [[4, 3, 1], [7, 6, 2], [5, 8, None]]
        if self.round_number == 18:
            my_puzzle = [[None, 4, 1], [3, 8, 5], [7, 6, 2]]
        if self.round_number == 19:
            my_puzzle = [[1, 3, 2], [4, 6, None], [7, 8, 5]]
        if self.round_number == 20:
            my_puzzle = [[7, 4, 1], [None, 3, 2], [6, 8, 5]]
        if formatting == 0:  # returns board
            return my_puzzle
        if formatting == 1:  # returns string
            my_puzzle_str = ''
            for i in range(0, 3):
                for j in range(0, 3):
                    my_puzzle_str = my_puzzle_str + str(my_puzzle[i][j])
            my_puzzle_str = my_puzzle_str.replace('None', '_')
            return my_puzzle_str

    def set_starting_player(self):
        self.starting_player = random.choice([player.id_in_group for player in self.get_players()])
        for player in self.get_players():
            player.is_starting_player = self.starting_player == player.id_in_group


class Player(BasePlayer):
    # variables for the puzzle
    move_history = models.LongStringField()
    is_starting_player = models.BooleanField()
    puzzle_solved = models.BooleanField(initial=False)
    # understanding questions
    uq1 = models.IntegerField (
        label = '1. Which of the following statements is true? ',
        widget = widgets.RadioSelect,
        choices = [[1, 'In this part, you and your partner will earn € 1 for each puzzle solved, which means you will earn € 1 for each puzzle solved.'],
                 [2, 'In this part, you and your partner will earn € 1 for each puzzle solved by the two of you, which means you will earn € 0.5 for each puzzle solved.'],])
    uq2 = models.IntegerField (
        label = '2. You and your partner ... ',
        widget = widgets.RadioSelect,
        choices = [[1, "you will work on the puzzles for 12 minutes by moving the tiles in turn. Which of you will make the first move is determined randomly at the beginning of each puzzle."],
                 [2, "You will work on the puzzles for 12 minutes. Which of you will make the first move is randomly determined at the beginning of this part and fixed later."],])    # count number of puzzles solved
    puzzles_solved_pt3 = models.IntegerField(initial=0)

    # error messages
    def uq1_error_message(self, uq1):
        print(uq1)
        if uq1 != 1:
            return self.session.config['uq_error']

    def uq2_error_message(self, uq2):
        print(uq2)
        if uq2 != 1:
            return self.session.config['uq_error']

    # a function to pass vars for later apps
    def pass_variable(self):
        self.participant.vars['puzzles_solved_pt3'] = self.puzzles_solved_pt3

    def vars_for_template(self):
        otherid = self.get_others_in_group()[0].participant.label
        return dict(otherid=otherid)

pt3/templates/pt3/Game.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Il puzzle {{ group.round_number }}
{% endblock %}

{% block styles %}
    <style type="text/css">
        table.slider_game {
            width: 300px;
            height: 300px;
            text-align: center;
            background-color: #000;
            font-size: 2em;
            border-collapse: unset;
            margin-left: auto;
            margin-right: auto;
        }

        .slider_game td {
            width: 100px;
            height: 100px;
        }

        .full {
            background-color: #ccc;
            cursor: pointer;
        }

        .empty {
            background-color: #fff;
        }

        .vspace {
            margin-top: 1em;
        }

        .center {
            text-align: center;
        }

        #message {
            font-weight: bold;
            display: inline-block;
        }

        .green {
            color: forestgreen;
        }

        .orange {
            color: orangered;
        }

    </style>
{% endblock %}

{% block content %}

    <div class="center vspace">
        <p>
            Il tuo partner è <strong>{{ otherid }}</strong><br>
        </p>
        <p>
        </p>

        <table class="slider_game" id="sgame_table"></table>

         <p id="message"></p>

        <input type="hidden" name="puzzle_solved" id="id_puzzle_solved" value="False">
        <input type="hidden" name="move_history" id="id_move_history">

        {% next_button %}
    </div>


{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        class SlidePuzzle {
            constructor(table_id, board) {
                this.table = document.getElementById(table_id);
                this.board = board;
                this.enabled = true;
                this.draw();
            }

            get_empty_field() {
                for (let row = 0; row < this.board.length; row++) {
                    for (let col = 0; col < this.board[row].length; col++) {
                        if (this.board[row][col] === null) {
                            return [row, col];
                        }
                    }
                }
            }

            get_movable_blocks() {
                let pos_empty_field = this.get_empty_field();
                let empty_row = pos_empty_field[0];
                let empty_col = pos_empty_field[1];

                // naive definition of row and col candidates
                let candidate_rows = [empty_row - 1, empty_row + 1];
                let candidate_cols = [empty_col - 1, empty_col + 1];

                let rows = [];
                let cols = [];

                // remove candidates outside of board
                for (let c_row = 0; c_row < candidate_rows.length; c_row++) {
                    if (candidate_rows[c_row] >= 0 && candidate_rows[c_row] < this.board.length) {
                        rows.push(candidate_rows[c_row]);
                    }
                }

                for (let c_col = 0; c_col < candidate_cols.length; c_col++) {
                    if (candidate_cols[c_col] >= 0 && candidate_cols[c_col] < this.board[0].length) { // assumes symmetric, min 1x1 board
                        cols.push(candidate_cols[c_col]);
                    }
                }

                // combine candidates with empty columns
                let block_pos = [];
                for (let i = 0; i < rows.length; i++) {
                    block_pos.push([rows[i], empty_col]);
                }

                for (let j = 0; j < cols.length; j++) {
                    block_pos.push([empty_row, cols[j]]);
                }

                return block_pos;
            }

            searchForArray(haystack, needle){
                var i, j, current;
                for(i = 0; i < haystack.length; ++i){
                    if(needle.length === haystack[i].length){
                        current = haystack[i];
                        for(j = 0; j < needle.length && needle[j] === current[j]; ++j);
                            if(j === needle.length)
                                return i;
                        }
                    }
                return -1;
            }

            move(pos, external=false) {
                if (!this.enabled) {
                    return false;
                }
                if (this.searchForArray(this.get_movable_blocks(this.board), pos) === -1) {
                    return false;
                }
                let empty = this.get_empty_field(this.board);
                this.board[empty[0]][empty[1]] = this.board[pos[0]][pos[1]];
                this.board[pos[0]][pos[1]] = null;
                this.draw();
                if (!external) {
                    let move_event = new CustomEvent('move', { detail: { from: pos, to: empty } });
                    this.table.dispatchEvent(move_event);
                }

                if (this.solved()) {
                    this.enabled = false;
                }
                return true;
            }

            clear() {
                const l = this.table.rows.length;
                for (let r = 0; r < l; r++) {
                    this.table.deleteRow(-1);
                }
            }

            draw() {
                this.clear();
                for (let r = 0; r < this.board.length; r++) {
                    let row = this.table.insertRow(-1);
                    for (let c = 0; c < this.board[0].length; c++) {
                        let cell = row.insertCell(-1);
                        let value;
                        if (this.board[r][c] == null) {
                            value = "";
                            cell.classList.add('empty');
                        } else {
                            value = this.board[r][c];
                            cell.classList.add('full');
                        }
                        cell.setAttribute('onclick', "sg.move(["+r+","+c+"])");
                        cell.innerHTML = value;
                    }
                }
            }

            solved() {
                let rows = this.board.length;
                let cols = this.board[0].length;

                if (this.board[rows - 1][cols - 1] != null) {
                    return false
                }

                for (let r = 0; r < rows; r++) {
                    for (let c = 0; c < cols; c++) {
                        if (this.board[r][c] !== (r * this.board[0].length) + (c+1)) {
                            if (r !== rows - 1 || c !== cols - 1) {
                                return false;
                            }
                        }
                    }
                }
                let solved_event = new Event('solved');
                this.table.dispatchEvent(solved_event);
                return true;
            }
        }


        // Websockets
        let ws_scheme = window.location.protocol === "https:" ? "wss" : "ws";
        let ws = new WebSocket(ws_scheme + '://' + window.location.host + "/pt3/" + js_vars.game_id + "/");

        // Handle any errors that occur.
        ws.onerror = function (error) {
            console.log('WebSocket Error: ' + error);
        };

        // Show a connected message when the WebSocket is opened.
        ws.onopen = function (event) {
            console.log('connected to puzzle socket');
        };

        // handle messages
        ws.onmessage = function (event) {
            data = JSON.parse(event.data);
            if (data.player !== js_vars.player_id) {
                green_message('È il tuo turno!');
                sg.enabled = true;
                sg.move(data.text.from, true);
                history.push(data.text);
                $('#id_move_history').val(JSON.stringify(history));
            }
        };

        // Show a disconnected message when the WebSocket is closed.
        ws.onclose = function (event) {
            console.log('disconnected from puzzle socket');
        };

        function send(type, message) {
            let msg = {
                type: type,
                text: message,
                player: js_vars.player_id
            };
            ws.send(JSON.stringify(msg));
            sg.enabled = false;
        }

        function green_message(msg) {
            let m = $('#message');
            m.removeClass('orange');
            m.addClass('green');
            m.text(msg);
        }

        function orange_message(msg) {
            let m = $('#message');
            m.removeClass('green');
            m.addClass('orange');
            m.text(msg);
        }

        // Game
        let board = js_vars.board;
        let sg = new SlidePuzzle('sgame_table', board);
        let history = [];

        sg.table.addEventListener('move', function (e) {
            send(e.type, e.detail);
            history.push(e.detail);
            $('#id_move_history').val(JSON.stringify(history));
            orange_message('Wait for your partner!');
        }, false);

        sg.table.addEventListener('solved', function () {
            $('#id_puzzle_solved').val('True');
            $('.otree-btn-next').show();
            green_message("You have solved the puzzle!");
        }, false);

        if (!js_vars.starting_player) {
            sg.enabled = false;
            orange_message('Wait for your partner!');
        } else {
            green_message("It's your turn!");
        }

        $('.otree-btn-next').hide();

    </script>
{% endblock %}

pt3/templates/pt3/Intro.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Instructions for part 3 of 3
{% endblock %}

{% block content %}
    <p>
        In this part, you will be solving puzzles with your partner
        for <strong> 12 minutes </strong> by moving the tiles in turn,
        and both you and your partner will earn
        <strong> {{session.config.pt3rate}} € for each puzzle </strong>
        that you will solve. There is a maximum of 20 puzzles that you and your partner
        you can solve (so the maximum gain is € 20 for each of you).
        As in part 2, one of you will be chosen at random to make the first
        move at the beginning of each puzzle.
    </p>
    <p>
        <strong> <u> Understanding questions </u> </strong>: <br>
        Before proceeding, answer the following comprehension questions.
        After answering, click Next.
    </p>
    {% formfields %}

    {% next_button %}

{% endblock %}

pt3/templates/pt3/Partner.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Your partner in part 3
{% endblock %}

{% block styles %}
    <style type="text/css">
        .slider_game td {
            width: 100px;
            height: 100px;
        }
        .vspace {
            margin-top: 1em;
        }

        .center {
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <p>
        Based on your choices and those of 7 other people,
        <strong> {{otherid}} </strong> became your partner for part 3.
    </p>

    {% next_button %}
{% endblock %}

pt3/templates/pt3/Proceed.html
{% extends "global/Page.html" %}
{% load otree static %}
{% block title %}
    The round with your partner is over
{% endblock %}
{% block content %}
    <p>
        The round with your partner is over. You have solved
        <strong> {{num_solved}} puzzle </strong>.
    </p>
    <p>
        Click Next to proceed.
    </p>
        {% next_button %}
{% endblock %}

pt3/templates/pt3/Ready.html
{% extends "global/Page.html" %}
{% load otree static %}
{% block title %}
    Get ready, the round with your partner will start shortly
{% endblock %}
{% block content %}
    <p>
        Be ready for the round with your partner.
    </p>
{% endblock %}