otreeutils/admin_extensions/urls.py
"""
Custom URLs that add hooks to session data monitor extensions.

Feb. 2021, Markus Konrad <markus.konrad@wzb.eu>
"""

from django.conf.urls import url
from otree.urls import urlpatterns

from . import views


# define patterns with name, URL pattern and view class
patterns_conf = {
    'SessionData': (r"^SessionData/(?P<code>[a-z0-9]+)/$", views.SessionDataExtension),
    'SessionDataAjax': (r"^session_data/(?P<code>[a-z0-9]+)/$", views.SessionDataAjaxExtension),
}

# exclude oTree's original patterns with the same names
urlpatterns = [pttrn for pttrn in urlpatterns if pttrn.name not in patterns_conf.keys()]

# add the patterns
for name, (pttrn, viewclass) in patterns_conf.items():
    urlpatterns.append(url(pttrn, viewclass.as_view(), name=name))

pt2/models.py
from otree.api import (
    models,
    widgets,
    BaseConstants,
    BaseSubsession,
    BaseGroup,
    BasePlayer,
    Currency as c,
    currency_range,
)

import random


author = 'Yuki Takahashi'

doc = """
Meeting and matching (main part)
"""


class Constants(BaseConstants):
    name_in_url = 'pt2'
    players_per_group = 2  # 8 people participating in each supergroup, so 4 groups.
    num_rounds = 7  # should be 7 rounds


class Subsession(BaseSubsession):
    # define variables to keep track of remaining players in each group in each round
    # we can increase the number of groups
    grp1ctr = models.IntegerField(initial=8)
    grp2ctr = models.IntegerField(initial=8)
    grp3ctr = models.IntegerField(initial=8)
    grp4ctr = models.IntegerField(initial=8)

    # perfect stranger matching based on the group membership and id within the group
    # defined in pt1grp, which was based on group_by_arrival_time()
    def group_by_arrival_time_method(self, waiting_players):
        import itertools  # import itertools for groupby()
        # define several functions to be used as sorting keys
        def sorting_key_both(pl):  # sort players by mygrp and mygid
            return [pl.participant.vars['mygrp'], pl.participant.vars['mygid']]
        def sorting_key_grp(pl):  # sort players by mygrp
            return pl.participant.vars['mygrp']
        def sorting_key_gid(pl):  # sort players by mygid
            return pl.participant.vars['mygid']
        waiting_players.sort(key=sorting_key_both)
        # create a list in which each element is a list of players belonging to the same mygrp, from grp1 to grpN
        waiting_players_grped = [list(g) for k, g in itertools.groupby(waiting_players, key=sorting_key_grp)]
        # sort the list so that longest list group comes first
        waiting_players_grped.sort(reverse=True, key=lambda x: len(x))
        print('waiting players with the largest group in the first:', waiting_players_grped)
        # create a list of mygrp
        waiting_players_key = [int(k) for k, g in itertools.groupby(waiting_players, key=sorting_key_grp)]
        print('waiting groups:', waiting_players_key)
        # choose the first group
        waiting_grp = waiting_players_grped[0]
        waiting_grp_num = waiting_players_grped[0][0].participant.vars['mygrp']
        # Make reference to group counter (shallow copy NOT working!)
        if waiting_grp_num == 1:
            grp_ctr = self.grp1ctr
        if waiting_grp_num == 2:
            grp_ctr = self.grp2ctr
        if waiting_grp_num == 3:
            grp_ctr = self.grp3ctr
        if waiting_grp_num == 4:
            grp_ctr = self.grp4ctr
        print('waiting players in the largest group:', waiting_grp)
        if len(waiting_grp) == grp_ctr:
            print('ALL THE REMAINING PLAYERS IN THIS GROUP ARE WAITING. SO WE WILL NOW DO MATCHING. THIS IS GROUP', waiting_grp_num, 'WITH THE NUMBER OF WAITNG PLAYERS', grp_ctr, 'IN ROUND', self.round_number)
            # deduct counter from grp counter
            if waiting_grp_num == 1:
                self.grp1ctr -= 2
            if waiting_grp_num == 2:
                self.grp2ctr -= 2
            if waiting_grp_num == 3:
                self.grp3ctr -= 2
            if waiting_grp_num == 4:
                self.grp4ctr -= 2
            waiting_grp.sort(key=sorting_key_gid)
            ind = [i.participant.vars['mygid'] for i in waiting_grp]
            print('Group ID indices (gid for remaining players in this group):', ind)
            if self.round_number == 1:
                # group structure: [[1, 2], [3, 4], [5, 6], [7, 8]]
                if 1 in ind and 2 in ind:
                    to_be_grpd = [waiting_grp[ind.index(1)], waiting_grp[ind.index(2)]]
                elif 3 in ind and 4 in ind:
                    to_be_grpd = [waiting_grp[ind.index(3)], waiting_grp[ind.index(4)]]
                elif 5 in ind and 6 in ind:
                    to_be_grpd = [waiting_grp[ind.index(5)], waiting_grp[ind.index(6)]]
                elif 7 in ind and 8 in ind:
                    to_be_grpd = [waiting_grp[ind.index(7)], waiting_grp[ind.index(8)]]
                else:
                    print('ERROR - CHECK CODE!')
            if self.round_number == 2:
                # group structure: [[2, 3], [4, 5], [6, 7], [8, 1]]
                if 2 in ind and 3 in ind:
                    to_be_grpd = [waiting_grp[ind.index(2)], waiting_grp[ind.index(3)]]
                elif 4 in ind and 5 in ind:
                    to_be_grpd = [waiting_grp[ind.index(4)], waiting_grp[ind.index(5)]]
                elif 6 in ind and 7 in ind:
                    to_be_grpd = [waiting_grp[ind.index(6)], waiting_grp[ind.index(7)]]
                elif 8 in ind and 1 in ind:
                    to_be_grpd = [waiting_grp[ind.index(8)], waiting_grp[ind.index(1)]]
                else:
                    print('ERROR - CHECK CODE!')
            if self.round_number == 3:
                # group structure: [[1, 3], [5, 7], [2, 4], [6, 8]]
                if 1 in ind and 3 in ind:
                    to_be_grpd = [waiting_grp[ind.index(1)], waiting_grp[ind.index(3)]]
                elif 5 in ind and 7 in ind:
                    to_be_grpd = [waiting_grp[ind.index(5)], waiting_grp[ind.index(7)]]
                elif 2 in ind and 4 in ind:
                    to_be_grpd = [waiting_grp[ind.index(2)], waiting_grp[ind.index(4)]]
                elif 6 in ind and 8 in ind:
                    to_be_grpd = [waiting_grp[ind.index(6)], waiting_grp[ind.index(8)]]
                else:
                    print('ERROR - CHECK CODE!')
            if self.round_number == 4:
                # group structure: [[1, 7], [2, 8], [3, 5], [4, 6]]
                if 1 in ind and 7 in ind:
                    to_be_grpd = [waiting_grp[ind.index(1)], waiting_grp[ind.index(7)]]
                elif 2 in ind and 8 in ind:
                    to_be_grpd = [waiting_grp[ind.index(2)], waiting_grp[ind.index(8)]]
                elif 3 in ind and 5 in ind:
                    to_be_grpd = [waiting_grp[ind.index(3)], waiting_grp[ind.index(5)]]
                elif 4 in ind and 6 in ind:
                    to_be_grpd = [waiting_grp[ind.index(4)], waiting_grp[ind.index(6)]]
                else:
                    print('ERROR - CHECK CODE!')
            if self.round_number == 5:
                # group structure: [[1, 4], [7, 2], [5, 8], [3, 6]]
                if 1 in ind and 4 in ind:
                    to_be_grpd = [waiting_grp[ind.index(1)], waiting_grp[ind.index(4)]]
                elif 7 in ind and 2 in ind:
                    to_be_grpd = [waiting_grp[ind.index(7)], waiting_grp[ind.index(2)]]
                elif 5 in ind and 8 in ind:
                    to_be_grpd = [waiting_grp[ind.index(5)], waiting_grp[ind.index(8)]]
                elif 3 in ind and 6 in ind:
                    to_be_grpd = [waiting_grp[ind.index(3)], waiting_grp[ind.index(6)]]
                else:
                    print('ERROR - CHECK CODE!')
            if self.round_number == 6:
                # group structure: [[4, 7], [2, 5], [8, 3], [6, 1]]
                if 4 in ind and 7 in ind:
                    to_be_grpd = [waiting_grp[ind.index(4)], waiting_grp[ind.index(7)]]
                elif 2 in ind and 5 in ind:
                    to_be_grpd = [waiting_grp[ind.index(2)], waiting_grp[ind.index(5)]]
                elif 8 in ind and 3 in ind:
                    to_be_grpd = [waiting_grp[ind.index(8)], waiting_grp[ind.index(3)]]
                elif 6 in ind and 1 in ind:
                    to_be_grpd = [waiting_grp[ind.index(6)], waiting_grp[ind.index(1)]]
                else:
                    print('ERROR - CHECK CODE!')
            if self.round_number == 7:
                # group structure: [[1, 5], [2, 6], [3, 7], [4, 8]]
                if 1 in ind and 5 in ind:
                    to_be_grpd = [waiting_grp[ind.index(1)], waiting_grp[ind.index(5)]]
                elif 2 in ind and 6 in ind:
                    to_be_grpd = [waiting_grp[ind.index(2)], waiting_grp[ind.index(6)]]
                elif 3 in ind and 7 in ind:
                    to_be_grpd = [waiting_grp[ind.index(3)], waiting_grp[ind.index(7)]]
                elif 4 in ind and 8 in ind:
                    to_be_grpd = [waiting_grp[ind.index(4)], waiting_grp[ind.index(8)]]
                else:
                    print('ERROR - CHECK CODE!')
            print('WE MATCH THE FOLLOWING PLAYERS:', to_be_grpd)
            return to_be_grpd


class Group(BaseGroup):
    # variables for the puzzle
    starting_player = models.IntegerField()
    move_history = models.LongStringField()
    move_histories_disagree = models.BooleanField()
    puzzle_solved = models.BooleanField(initial=False)

    # verify that the moves are stored correctly
    def verify_stored_moves(self):
        p1 = self.get_player_by_id(1)
        p2 = self.get_player_by_id(2)
        if p1.move_history == p2.move_history:
            self.move_history = p1.move_history
            self.move_histories_disagree = False
        else:
            self.move_histories_disagree = True
        if p1.puzzle_solved or p2.puzzle_solved:
            self.puzzle_solved = True
            p1.puzzle_solved = True
            p2.puzzle_solved = True
        else:
            self.puzzle_solved = False


    # define puzzles to play
    def puzzle_to_play(self, formatting):
        if self.round_number == 1:
            my_puzzle = [[2, 4, 3], [1, 5, 6], [7, 8, None]]
        if self.round_number == 2:
            my_puzzle = [[None, 1, 5], [4, 3, 2], [7, 8, 6]]
        if self.round_number == 3:
            my_puzzle = [[2, 3, None], [1, 8, 5], [4, 7, 6]]
        if self.round_number == 4:
            my_puzzle = [[1, 6, 2], [4, 3, 8], [7, 5, None]]
        if self.round_number == 5:
            my_puzzle = [[1, 3, 6], [5, 2, 8], [4, 7, None]]
        if self.round_number == 6:

slider_individual/models.py
from otree.api import (
    models,
    widgets,
    BaseConstants,
    BaseSubsession,
    BaseGroup,
    BasePlayer,
    Currency as c,
    currency_range,
)



doc = """
Individual round slider task
"""


class Constants(BaseConstants):
    name_in_url = 'slider_task'
    players_per_group = None
    num_rounds = 1


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    # define puzzles to play
    def puzzle_to_play(self, formatting):
        my_boards = [
            [[1, 2, 3], [4, 5, 6], [7, None, 8]],
            [[1, 2, 3], [4, None, 5], [7, 8, 6]],
            [[1, 2, 3], [4, 6, None], [7, 5, 8]],
            [[None, 2, 3], [1, 4, 5], [7, 8, 6]],
            [[1, 3, 6], [4, 2, None], [7, 5, 8]],
            [[1, 2, 3], [7, 4, 6], [5, 8, None]],
            [[1, 2, 3], [7, 4, None], [5, 8, 6]],
            [[2, 5, 3], [1, 7, 6], [4, 8, None]],
            [[4, 1, 3], [7, 2, None], [8, 6, 5]],
            [[None, 1, 3], [5, 2, 7], [4, 8, 6]],
            [[2, None, 6], [1, 3, 8], [4, 5, 7]],
            [[4, 1, None], [8, 3, 2], [5, 7, 6]],
            [[1, 5, 2], [None, 7, 6], [3, 4, 8]],
            [[2, 3, 8], [7, 1, 4], [None, 6, 5]],
            [[2, 7, 3], [5, 1, None], [4, 8, 6]],
        ]
        if formatting == 0:  # returns board
            return my_boards
        if formatting == 1:  # returns string
            my_boards_str = []
            for k in range(0, 15):
                my_puzzle_str = ''
                for i in range(0, 3):
                    for j in range(0, 3):
                        my_puzzle_str = my_puzzle_str + str(my_boards[k][i][j])
                my_puzzle_str = my_puzzle_str.replace('None', '_')
                my_boards_str.append(my_puzzle_str)
            return my_boards_str

    # puzzle info
    puzzles_solved_pt1 = models.IntegerField()
    puzzle_histories = models.LongStringField()

    # a function to pass vars for later apps
    def pass_variable(self):
        self.participant.vars['puzzles_solved_pt1'] = self.puzzles_solved_pt1

    # a function to add tentative earnings to the build-in payff variable
    def add_payoff(self):
        self.payoff += round(self.session.config['pt1rate'] * self.puzzles_solved_pt1, 2)

slider_individual/templates/slider_individual/Game.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
{% endblock %}

{% block styles %}
    <style type="text/css">
        table.slider_game {
            width: 300px;
            height: 300px;
            text-align: center;
            background-color: #000;
            font-size: 2em;
            border-collapse: unset;
            margin-left: auto;
            margin-right: auto;
        }

        .slider_game td {
            width: 100px;
            height: 100px;
        }

        .full {
            background-color: #ccc;
            cursor: pointer;
        }

        .empty {
            background-color: #fff;
        }

        .vspace {
            margin-top: 1em;
        }

        .center {
            text-align: center;
        }

        #message {
            font-weight: bold;
            display: inline-block;
        }

        .green {
            color: forestgreen;
        }

        .orange {
            color: orangered;
        }

    </style>
{% endblock %}

{% block content %}

    <div class="center vspace">
        <p>

        </p>

        <table class="slider_game" id="sgame_table"></table>

         <p id="message"></p>

        <input type="hidden" name="puzzles_solved_pt1" id="id_puzzle_solved" value=0>
        <input type='hidden' name='puzzle_histories' id='id_puzzle_histories'>

    </div>


{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        class SlidePuzzle {
            constructor(table_id, board) {
                this.table = document.getElementById(table_id);
                this.board = board;
                this.enabled = true;
                this.draw();
            }

            set_board(board) {
                this.board = board;
                this.enabled = true;
                this.draw();
            }

            get_empty_field() {
                for (let row = 0; row < this.board.length; row++) {
                    for (let col = 0; col < this.board[row].length; col++) {
                        if (this.board[row][col] === null) {
                            return [row, col];
                        }
                    }
                }
            }

            get_movable_blocks() {
                let pos_empty_field = this.get_empty_field();
                let empty_row = pos_empty_field[0];
                let empty_col = pos_empty_field[1];

                // naive definition of row and col candidates
                let candidate_rows = [empty_row - 1, empty_row + 1];
                let candidate_cols = [empty_col - 1, empty_col + 1];

                let rows = [];
                let cols = [];

                // remove candidates outside of board
                for (let c_row = 0; c_row < candidate_rows.length; c_row++) {
                    if (candidate_rows[c_row] >= 0 && candidate_rows[c_row] < this.board.length) {
                        rows.push(candidate_rows[c_row]);
                    }
                }

                for (let c_col = 0; c_col < candidate_cols.length; c_col++) {
                    if (candidate_cols[c_col] >= 0 && candidate_cols[c_col] < this.board[0].length) { // assumes symmetric, min 1x1 board
                        cols.push(candidate_cols[c_col]);
                    }
                }

                // combine candidates with empty columns
                let block_pos = [];
                for (let i = 0; i < rows.length; i++) {
                    block_pos.push([rows[i], empty_col]);
                }

                for (let j = 0; j < cols.length; j++) {
                    block_pos.push([empty_row, cols[j]]);
                }

                return block_pos;
            }

            searchForArray(haystack, needle){
                var i, j, current;
                for(i = 0; i < haystack.length; ++i){
                    if(needle.length === haystack[i].length){
                        current = haystack[i];
                        for(j = 0; j < needle.length && needle[j] === current[j]; ++j);
                            if(j === needle.length)
                                return i;
                        }
                    }
                return -1;
            }

            move(pos, external=false) {
                if (!this.enabled) {
                    return false;
                }
                if (this.searchForArray(this.get_movable_blocks(this.board), pos) === -1) {
                    return false;
                }
                let empty = this.get_empty_field(this.board);
                this.board[empty[0]][empty[1]] = this.board[pos[0]][pos[1]];
                this.board[pos[0]][pos[1]] = null;
                this.draw();
                if (!external) {
                    let move_event = new CustomEvent('move', { detail: { from: pos, to: empty } });
                    this.table.dispatchEvent(move_event);
                }

                if (this.solved()) {
                    this.enabled = false;
                }
                return true;
            }

            clear() {
                const l = this.table.rows.length;
                for (let r = 0; r < l; r++) {
                    this.table.deleteRow(-1);
                }
            }

            draw() {
                this.clear();
                for (let r = 0; r < this.board.length; r++) {
                    let row = this.table.insertRow(-1);
                    for (let c = 0; c < this.board[0].length; c++) {
                        let cell = row.insertCell(-1);
                        let value;
                        if (this.board[r][c] == null) {
                            value = "";
                            cell.classList.add('empty');
                        } else {
                            value = this.board[r][c];
                            cell.classList.add('full');
                        }
                        cell.setAttribute('onclick', "sg.move(["+r+","+c+"])");
                        cell.innerHTML = value;
                    }
                }
            }

            solved() {
                let rows = this.board.length;
                let cols = this.board[0].length;

                if (this.board[rows - 1][cols - 1] != null) {
                    return false;
                }

                for (let r = 0; r < rows; r++) {
                    for (let c = 0; c < cols; c++) {
                        if (this.board[r][c] !== (r * this.board[0].length) + (c+1)) {
                            if (r !== rows - 1 || c !== cols - 1) {
                                return false;
                            }
                        }
                    }
                }
                let solved_event = new Event('solved');
                this.table.dispatchEvent(solved_event);
                return true;
            }
        }


        function green_message(msg) {
            let m = $('#message');
            m.removeClass('orange');
            m.addClass('green');
            m.text(msg);
        }

        function orange_message(msg) {
            let m = $('#message');
            m.removeClass('green');
            m.addClass('orange');
            m.text(msg);
        }

        // Game
        // Define a list of boards to be played one after the other.
        // Make sure these can be solved!
        // You could also come up with a function that generates solvable boards...
        let boards = js_vars.boards;

        let current_board = 0;
        let histories = [];
        for (board in boards) {
            histories.push([]);
        }
        let num_solved = 1;
        // initialize the game with the first board from the list.
        let sg = new SlidePuzzle('sgame_table', boards[current_board]);

        sg.table.addEventListener('move', function (e) {
            histories[current_board].push(e.detail);
            $('#id_puzzle_histories').val(JSON.stringify(histories));
        }, false);

        sg.table.addEventListener('solved', function () {
            $('#id_puzzle_solved').val(num_solved);
            green_message("You have solved the puzzle!");
            window.setTimeout(function() {
                // if it was solved, we clear the board, take the next board and reset the game
                if (current_board + 1 < boards.length) {
                    num_solved +=1;
                    current_board +=1;
                    sg.clear();
                    sg.set_board(boards[current_board]);
                    green_message("");
                } else {
                    orange_message("You have solved all the puzzles!");
                }
            }, 2000);
        }, false);

    </script>
{% endblock %}

slider_individual/templates/slider_individual/Intro.html
{% extends "global/Page.html" %}
{% load otree static %}
<!-- {% load custom_tags %} -->

{% block styles %}
    <style>
      table {
        border-collapse: separate;
        border-spacing: 15px 0;
      }
    </style>
{% endblock %}

{% block title %}
    Slider Task
{% endblock %}

{% block content %}
    <p>
        In this part, you will solve slider puzzles on your own.
        You have <strong> {{roundlength}} minutes</strong> to solve
        as many puzzles as possible (up to a maximum of 15 puzzles).
        You will earn <strong> ${{session.config.pt1rate}}</strong> per puzzle solved, if this task is randomly chosen for payment.
    </p>

    <!-- {% delayed_next wait=30000 label='NEXT'%} -->
    {% delayed_next wait=50 label='NEXT'%}

{% endblock %}

slider_individual/templates/slider_individual/Proceed.html
{% extends "global/Page.html" %}
{% load otree static %}
<!-- {% load custom_tags %} -->

{% block title %}

{% endblock %}
{% block content %}
    <p>
        Task 1 is over. You solved
        <strong> {{player.puzzles_solved_pt1}} </strong> puzzles correctly.
    </p>
    <p>
        Click Next to proceed.
    </p>

    <!-- {% delayed_next wait=30000 label='NEXT'%} -->

    {% delayed_next wait=5000 label='NEXT'%}
{% endblock %}

slider_individual/templates/slider_individual/Ready.html
{% extends "global/Page.html" %}
{% load otree static %}
{% block title %}
    Get ready, the slider task will begin in just a moment.
{% endblock %}
{% block content %}

{% endblock %}